#linguage: pt

Funcionalidade: Configurar Produto

Cliente da EBAC-SHOP.
Configurar meu produto de acordo com meu tamanho e gosto.
escolher a quantidade.
depois inserir no carrinho.


Critérios de aceitação:

Cenário: Tela de produtos

Dado Escolha de cores,tamanho e quantidade são obrigatórias

Quando adicionadas corretamente suas escolhas

E enseridas até 10 produtos 

Então seram inseridas no carrinho para a compra 




